# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python312:
      python.version: '3.12.1'
  maxParallel: 1

steps:
- checkout: self
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install robotframework
    pip install robotframework-seleniumlibrary
    pip install chromedriver-py
    pip install pytest pytest-azurepipelines
    pip install pytest-cov
    echo $(System.DefaultWorkingDirectory)
    dir $(System.DefaultWorkingDirectory)
  displayName: 'Install dependencies'

- powershell: |
    # Display the path where Git cloned the repository
      Write-Host "Repository is cloned at: $env:BUILD_SOURCESDIRECTORY"
      echo $(System.DefaultWorkingDirectory)
      dir $(System.DefaultWorkingDirectory)
    # Run Robot Framework tests
    robot  --xunit output.xml $(System.DefaultWorkingDirectory)\OpenGoogle.robot
  displayName: 'Run Robot Framework script'

- task: PublishTestResults@2
  inputs:
      testResultsFiles: '$(System.DefaultWorkingDirectory)\output.xml'
      testRunTitle: 'Robot Framework Tests'
      testRunSystem: 'Robot Framework'
      failTaskOnFailedTests: true


