# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'vs2022-win2023
strategy:
  matrix:
    Python312:
    python.version: '3.12.1'
    maxParallel: 1

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

- script: |
    python -m pip install --upgrade pip
    pip install robotframework-seleniumlibrary
    pip install chromedriver-py
  displayName: 'Install dependencies'
  
  - powershell: robot --pythonpath . -x outputxunit.xml OpenGoogle.robot
    displayName: 'Run Robot Scripts'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: outputxunit.xml
      searchFolder: 'D:\a\1\s\'
      condition: succeededOrFailed()
      displayName: 'Publish Test Results outputxunit.xml'