# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: windows-latest
strategy:
  matrix:
    Python312:
      python.version: '3.12.1'
  maxParallel: 1

steps:
- checkout: self
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- powershell: |
    # Display the path where Git cloned the repository
      Write-Host "Repository is cloned at: $env:BUILD_SOURCESDIRECTORY"
      Get-ChildItem D:\a\ recurse
      Write-Host "Printing the build source at: $env:BUILD_SOURCESDIRECTORY"
      echo "Listing contents of Agent.ToolsDirectory:"
      Write-Host "Printing the agent tools"
      dir "$(Agent.ToolsDirectory)" Recurse
      echo $(System.DefaultWorkingDirectory)
      # dir $(System.DefaultWorkingDirectory)
      # echo "Found tool in cache: Python $(PythonVersion) $(Architecture)"
      # echo "Prepending PATH environment variable with directory: $(Agent.ToolsDirectory)\python\$(PythonVersion)\$(Architecture)"
      # echo "Prepending PATH environment variable with directory: $(Agent.ToolsDirectory)\python\$(PythonVersion)\$(Architecture)\Scripts"
      # echo "Prepending PATH environment variable with directory: $env:APPDATA\Python\Python$(PythonVersion)\Scripts"
    # Run Robot Framework tests
    robot  --xunit output.xml $(System.DefaultWorkingDirectory)\OpenGoogle.robot
  displayName: 'Run Robot Framework script'

- script: |
    echo "Found tool in cache: Python $(PythonVersion) $(Architecture)"
    echo "Prepending PATH environment variable with directory: $(Agent.ToolsDirectory)\python\$(PythonVersion)\$(Architecture)"
    echo "Prepending PATH environment variable with directory: $(Agent.ToolsDirectory)\python\$(PythonVersion)\$(Architecture)\Scripts"
    echo "Prepending PATH environment variable with directory: $env:APPDATA\Python\Python$(PythonVersion)\Scripts"
  displayName: 'Print Python Tool Cache Details'

- script: |
    python -m pip install --upgrade pip
    pip install robotframework
    pip install robotframework-seleniumlibrary
    pip install chromedriver-py
    pip install pytest pytest-azurepipelines
    pip install pytest-cov
    echo $(System.DefaultWorkingDirectory)
    dir $(System.DefaultWorkingDirectory)
  displayName: 'Install dependencies'

- powershell: |
    # Display the path where Git cloned the repository
      Write-Host "Repository is cloned at: $env:BUILD_SOURCESDIRECTORY"
      echo $(System.DefaultWorkingDirectory)
      dir $(System.DefaultWorkingDirectory)
    # Run Robot Framework tests
    robot  --xunit output.xml $(System.DefaultWorkingDirectory)\OpenGoogle.robot
  displayName: 'Run Robot Framework script'

- task: PublishTestResults@2
  inputs:
      testResultsFiles: '$(System.DefaultWorkingDirectory)\output.xml'
      testRunTitle: 'Robot Framework Tests'
      testRunSystem: 'Robot Framework'
      failTaskOnFailedTests: true


